---
- name: Deploy Flask Application Securely
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install dependencies from requirements.txt
      pip:
        requirements: /home/delaila/MonProjetSecurite/MonProjetSecurite/requirements.txt

    - name: Configure firewall to allow access on port 5000 (Flask default)
      ufw:
        rule: allow
        name: 'Flask'
        port: '5000'
        proto: tcp

    - name: Start the Flask application
      shell: |
        cd /home/delaila/MonProjetSecurite/MonProjetSecurite
        nohup python3 app.py &
      args:
        chdir: /home/delaila/MonProjetSecurite/MonProjetSecurite
