---
- name: Deploy Flask Application
  hosts: localhost
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv
        - git

    - name: Clone Flask app repository
      git:
        repo: 'git@github.com:dalal-1/MonProjetSecurite.git'
        dest: '/home/delaila/monprojet'
        version: master
        key_file: '/home/delaila/.ssh/id_rsa'  # Assurez-vous que la clé SSH est utilisée pour l'authentification

    - name: Create virtual environment
      command:
        cmd: python3 -m venv /home/delaila/monprojet/venv
        creates: /home/delaila/monprojet/venv

    - name: Install requirements
      pip:
        requirements: /home/delaila/monprojet/requirements.txt
        virtualenv: /home/delaila/monprojet/venv

    - name: Start Flask application
      command:
        cmd: "/home/delaila/monprojet/venv/bin/python /home/delaila/monprojet/app.py"

