---
- name: Deploy Flask Application
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - git

    - name: Clone Flask app repository
      git:
        repo: 'https://github.com/ton_nom_utilisateur/MonProjetSecurite.git'
        dest: /home/ubuntu/monprojet
        version: master

    - name: Set up virtual environment
      command: python3 -m venv /home/ubuntu/monprojet/venv

    - name: Install dependencies from requirements.txt
      pip:
        requirements: /home/ubuntu/monprojet/requirements.txt
        virtualenv: /home/ubuntu/monprojet/venv

    - name: Start the Flask app
      command: /home/ubuntu/monprojet/venv/bin/gunicorn -b 0.0.0.0:8000 app:app
      args:
        chdir: /home/ubuntu/monprojet
